### ISSUE TITLE
[Feature Request] Customize icons and order

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#1]
Add ability to change the order of icons and customize the icons themselves.

**Comment by maykar** [comment]
So in the original feature request I was talking about the menu, notification, voice, and option buttons, but I do like your idea and if I come up with a good way to implement it I will. 

As for the original request, I don't think it's worth the trouble so I'm closing this. If I add the functionality you're looking for I will post here again so you will be notified.

**Comment by rpitera** [comment]
Thanks for even considering it.  And I'll say it again - I really _can't_ imagine ever going back to the normal header since you developed this.  Thanks again for all your hard work.
