### ISSUE TITLE
[Feature Request] Tab Exceptions

### ISSUE THREAD

**Issue by kloggy** [maykar/compact-custom-header#104]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Describe the solution you'd like
Would it be possible to have Exceptions Config based on tab?

I'm think specifically of 'clock'. I have a date/time card on my primary view so would like to have no clock on the header for just that one view.

No big deal if this isn't possible, it was just a thought....

**Additional Context**
None

**Comment by maykar** [comment]
This unfortunately causes more problems than it solves. I've given it a try, but it requires re-rendering of config and header elements on each tab change and leads to a laggy & buggy experience.
