### ISSUE TITLE
[Feature Request] Swiping Left or Right In Mobile Phone To Access Previous/Next Icon Tab Contents

### ISSUE THREAD

**Issue by jerrychong25** [maykar/compact-custom-header#105]
**Is your feature request related to a problem? Please describe.**
I have implemented your custom header into my HA.

However, I found out one small issue.

When viewing from Mobile Phone, I can’t swipe left or right to switch between these multiple icon tabs, which is slightly inconveniences for mobile app users.

I still need to click these icons in order to access another icon tab content.

**Describe the solution you'd like**
Allow configuration of swiping left/right hand gesture to access previous or next icon tab contents.

**Additional Context**
Is there any ways to implement swipe left or right for access icon previous/next tab contents?

Thanks.

**Comment by maykar** [comment]
I decided to just contribute to another lovelace project that was doing this already and just submit a PR to fix some of the issues they were having. Until they pull it you can find my updated fork of their project here:

https://github.com/maykar/lovelace-swiper

**Comment by jerrychong25** [comment]
> I decided to just contribute to another lovelace project that was doing this already and just submit a PR to fix some of the issues they were having. Until they pull it you can find my updated fork of their project here:
> 
> https://github.com/maykar/lovelace-swiper

Thanks for this solution.

Just curious, is there any way to fix the known issue?
`After interacting with a view there is a period of about 3-5 seconds before you are able to swipe again.`

Thanks.

**Comment by maykar** [comment]
I have been unable to find a workaround to the delay issue, not sure if there is one, but I'll keep hacking away at it.

**Comment by maykar** [comment]
I've rewritten the swiper and made a new project. It no longer has the delay issue, give it a shot:

https://github.com/maykar/lovelace-swipe-navigation

**Comment by iantrich** [comment]
Should consider contributing this to core ;)

**Comment by jerrychong25** [comment]
> I've rewritten the swiper and made a new project. It no longer has the delay issue, give it a shot:
> 
> https://github.com/maykar/lovelace-swipe-navigation

Thanks. This is awesome!
