### ISSUE TITLE
Conditionally Hide Tabs

### ISSUE THREAD

**Issue by apop880** [maykar/compact-custom-header#110]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be nice to be able to show/hide tabs based on conditions.

**Additional Context**
For example, I have a view with some of my Chromecast devices that is really only useful if casting is taking place. It would be nice to have the option available to hide the view completely when nothing is being cast.

**Comment by maykar** [comment]
Now possible in the latest release with [Conditional Styling Templates](https://github.com/maykar/compact-custom-header/wiki/Conditional-Styling-Templates).
