### ISSUE TITLE
log error

### ISSUE THREAD

**Issue by mclaudiopt** [maykar/compact-custom-header#122]
hello
when i boot in hassio, i see the following error on the log

019-05-27 09:26:03 WARNING (MainThread) [pyupdate.log] Common(get_repo_data) - Custom URL should be json, not .js - 'https://raw.githubusercontent.com/maykar/compact-custom-header/master/compact-custom-header.js'

how can i correct?
tyanks

**Comment by maykar** [comment]
Are you using HACS? Did you follow the HACS [installation instructions](https://github.com/maykar/compact-custom-header/wiki/Installation) for this card?
