### ISSUE TITLE
[Feature Request] Compatibility with hacs ?

### ISSUE THREAD

**Issue by Bastiencc** [maykar/compact-custom-header#124]
**Is your feature request related to a problem? Please describe.**
Hi

First of all, thanks for the great works !
Custom updater will be stopped soon, HACS will replace it. it will be great if this plugin could be added to HACS (https://github.com/custom-components/hacs)

Thanks !

**Describe the solution you'd like**
add to HACS

**Additional Context**

**Comment by maykar** [comment]
This already compatible and instructions on how to add it to HACS are in the [installation instructions](https://github.com/maykar/compact-custom-header/wiki/Installation).
