### ISSUE TITLE
Edit add-on help text to include type: module

### ISSUE THREAD

**Issue by xbmcnut** [maykar/compact-custom-header#136]
## Describe the bug:

There is a discrepancy between the [Github](https://maykar.github.io/compact-custom-header/Main-Config-Options/) installation docs and the ones located inside the add-on for HACS. The HACS version does not show `type: module` even though this is required creating confusion. Can this be added or is that coming directly from HACS?

## Config YAML:
```yaml
<!-- Paste your lovelace code for the card after this line -->

```
## HA, Card, and Browser Versions:

1.0.4b9

![image](https://user-images.githubusercontent.com/1492137/60259064-8163fa80-992a-11e9-82eb-d720acfb0d08.png)

**Comment by maykar** [comment]
Added with latest release

**Comment by xbmcnut** [comment]
That was fast! Thanks.
