### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by peterhoeg** [maykar/compact-custom-header#14]
Please tag your releases so we can track them via the atom feed.

**Comment by maykar** [comment]
This doesn't make sense for this type of project for a few reasons, but if you'd like to be notified of releases there are other methods including tracker-card.

**Comment by peterhoeg** [comment]
> This doesn't make sense for this type of project

I beg to differ. On NixOS I pull in other cards based on their releases which means I don't have to pin a particular commit in order to get reproducible builds. 

This is obviously your project to do with as you please, but it would make things easier for downstream users.

**Comment by maykar** [comment]
I guess my biggest issue with this is that this won't always point to one project. This will hold all of my "custom-lovelace" projects. Any time there is an update to one a new release would be made and each release would then need its own separate version number from the projects contained within.

**Comment by peterhoeg** [comment]
> I guess my biggest issue with this is that this won't always point to one project. 

That would be an issue. For this to make sense it would have to be one project, one repo.

**Comment by maykar** [comment]
Changed my mind and decided to go ahead with this, will be creating releases from now on and will just do one project per repo. Thanks @peterhoeg!

**Comment by peterhoeg** [comment]
That's great! And I see 0.2.5 was just cut.
