### ISSUE TITLE
Screensaver feature

### ISSUE THREAD

**Issue by jawaite123** [maykar/compact-custom-header#145]
**Is your feature request related to a problem? Please describe.**
I have an ipad on the wall to control my smart devices and the screen stays on all the time. The iOS has a sleep function but that makes you hit the button and swipe to open. 

**Describe the solution you'd like**
The lovelace screen could use javascript/css to black out the screen after a set amount of time. Then if you tap the screen it would "wake up". 

**Additional Context**
should be able to set the amount of second/minutes to go to sleep.

**Comment by maykar** [comment]
This feature was just added to [@thomasloven's](https://github.com/thomasloven/) project [browser_mod](https://github.com/thomasloven/hass-browser_mod). It's called [black out](https://github.com/thomasloven/hass-browser_mod#blackout). He has plans to expand on it to allow for adding lovelace cards as part of the "screensaver". I feel like his project is better suited for such a feature.

**Comment by jawaite123** [comment]
Oh, wow, missed that. Thanks!
