### ISSUE TITLE
Error after "Configure UI"

### ISSUE THREAD

**Issue by maykar** [maykar/compact-custom-header#151]
## Describe the bug:
Error after exiting Configure UI. Requires reload to fix.

## Config YAML:
```yaml
```
## HA and/or Browser Error:
```
Uncaught TypeError: Cannot read property 'querySelector' of null
    at styleButtons
```

**Comment by whxciotw** [comment]
I am still facing this issue after update to 1.2.0

`Uncaught TypeError: Cannot read property 'querySelector' of null`
