### ISSUE TITLE
CCH seems to fails with the latest beta (0.96.0b0)

### ISSUE THREAD

**Issue by vandalon** [maykar/compact-custom-header#159]
## Describe the bug:
CCH does not seem to load, throwing this error in the home assistant logging.

## HA and/or Browser Error:
```
2019-07-11 19:55:10 ERROR (MainThread) [frontend.js.latest.201907100] http://hass.wiebel.nl:8123/community_plugin/compact-custom-header/compact-custom-header.js:210:46 TypeError: null is not an object (evaluating 'root
    .querySelector("hui-notification-drawer")
    .shadowRoot')
```
## HA, Card, and Browser Versions:
HA 0.96.0b0, CCH 1.2.1 and any browser

It seems a bit obvious because the HA-team made a lot of change to the ui :)

**Comment by maykar** [comment]
I am aware and will have a "beta" version I've been working on up later today, few kinks to work out first. I will post here to let you know.

**Comment by acordill** [comment]
Beta works well.  Only small problem I have is getting rid of the menu button, I basically have two of them now.

**Comment by maykar** [comment]
Yeah, that's just how Lovelace looks now. Unless you're on a mobile device or your window is slim you will see two. You could use CCH to fix this by making an exception to hide the menu button depending on the width of your screen using a media_query.

**Comment by maykar** [comment]
```yaml 
cch:
  exceptions:
    - conditions:
        media_query: "(min-width: 1400px)"
      config:
        menu: hide
```

Like that for example. You could use a user_agent as well.
