### ISSUE TITLE
Confused by documentation

### ISSUE THREAD

**Issue by brahmafear** [maykar/compact-custom-header#17]
The readme lists all the config options but does not specify where these are supposed to be set.

**Comment by maykar** [comment]
Not sure what you're having trouble with. The config options are set like any other lovelace card and there are a couple of examples at the end of the readme

**Comment by brahmafear** [comment]
Apologies for still not following.  

I only see examples for the user-agent filtering.  Could an example be provided that lists all of the config options?

**Comment by brahmafear** [comment]
I see.  Perhaps my confusion is related to this not really being a card - but a modification to the javascript on the main page.  Ex. the kiosk.js file you mention as inspiration has no such card configuration.  Regardless, perhaps a single listing of a non-user-agent example of use of the card would help guide others.  The documentation for all other cards I've seen include something similar.  Finally, **thanks** for making this and sharing.

**Comment by maykar** [comment]
No worries, I'll add an example to the readme. Understand the confusion, made this a "card" to avoid some of the issues of the kiosk.js method, one of which is easier configuration ironically  :)

**Comment by maykar** [comment]
Added example to readme.

One of the reasons I hesitate to add examples like this is that people will just copy and paste it into their config without understanding what it all does, even with the disclaimer to not do so.
