### ISSUE TITLE
CCH not working on WallPanel on AmazonFire tablet

### ISSUE THREAD

**Issue by signaleleven** [maykar/compact-custom-header#173]
## Describe the issue:
This might be a bit specific, but I have no idea how to debug it.
I use the application [WallPanel](https://github.com/thanksmister/wallpanel-android) to open the HA UI on a tablet on the wall.
CCH loads and works everywhere except on this device, where it is simply not loaded.
I am not setting up any exception, and it works on any other device, including on WallPanel on my phone.
I imagine that WallPanel is using whatever WebView the system provides, and the weird android on Amazon Fire has a weird one. But since I don't have any "dev tools" in it, I don't know how to debug it.

## Config YAML:

```yaml
# Any config :) It works on other devices
```
## HA and/or Browser Error:
The HA ui is displayed without any customization

## Versions and Browser:
CCH 1.3.1
HA 0.96.1
WallPanel browser

I realize this is impossible to troubleshoot without my exact hardware/software setup, so I am mostly putting it here as a hail mary.
But if you can think of any feature in the code that can justify it being ignored on old android Webview components (assuming that's the problem...)...

Great little mod, I hope some of these options will make it into the upstream Lovelace

**Comment by maykar** [comment]
CCH may not function on some older/unsupported browsers. Unfortunately, WebView fits into the unsupported category. There may be ways to get around this with alternative browsers, side loading a browser, or rooting, but I cannot offer support as I do not own one of these devices and cannot accommodate every browser/device.

**Comment by maykar** [comment]
I've updated the troubleshooting guide to be more clear with this and removed the mention of the older solution as it no longer works with recent versions of CCH.

**Comment by maykar** [comment]
@signaleleven I'm going to walk back on this a bit. Please, give this a try:

CCH for older/unsupported devices. 
[compact-custom-header.js](https://gist.github.com/maykar/278cf3d81e99a7594d4a0d1677fe981f)

Let me know if it works for you, if so I will either merge this to master or at least update docs to point to it.

Since I'm using a different method for the UI config now, I realized that I no longer need to use methods that are preventing these devices from working.

**Comment by signaleleven** [comment]
I'll test this on the weekend. Thanks!

**Comment by maykar** [comment]
If you're still having issues keep an eye on this gist:
https://gist.github.com/pjv/521073b982e37418339afbf420691310

I've modified CCH so that @pjv would be able to work his magic and get his legacy version up and running again. I imagine it will be updated soon.

**Comment by maykar** [comment]
If anyone was still having issues with this I just updated the legacy device version. Found here: [CCH for older/unsupported devices.](https://github.com/maykar/compact-custom-header/issues/185)

**Comment by signaleleven** [comment]
Apologies, I could not try it yet.

**Comment by signaleleven** [comment]
Not  working either :(
But I'm really using a unique combo of OS+browser, I'm good, don't worry :)
