### ISSUE TITLE
[Feature Request] Disable "compact" header, retain other features.

### ISSUE THREAD

**Issue by dy1io** [maykar/compact-custom-header#176]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I know this is more of a personal preference thing, but I prefer the look of the standard lovelace header in most cases. However, all of the other features are incredibly useful and are how I found this (such as kiosk mode, showing/hiding views, etc.). I would like to see an option added where I can keep the look of the original header, but retain all of the other features. And/or an option where the size of the header is consistent with other areas of Home Assistant so that the header is the same height as the History tab or the Log.

**Comment by maykar** [comment]
So this is one I keep coming back to. CCH kind of got away from me when it comes to features and ballooned into much more than cosmetic changes to the header.  Making the "compact" portion an option feels like I should finally just drop the current branding and make this into a new project. Something like "Lovelace Enhancer".

Everything in CCH is built on top of the fact that the header has been "compacted" so this will be a bit of work, but I wanted to let you know that this is coming.

**Comment by dy1io** [comment]
I can definately understand the time. Looking forward to this, I appreciate your hard work.

Also this
![image](https://user-images.githubusercontent.com/9081070/62178112-a1b21b00-b315-11e9-9091-5ce60fa8c0fd.png)

**Comment by JayBigGuy10** [comment]
> So this is one I keep coming back to. CCH kind of got away from me when it comes to features and ballooned into much more than cosmetic changes to the header.  Making the "compact" portion an option feels like I should finally just drop the current branding and make this into a new project. Something like "Lovelace Enhancer".
> Everything in CCH is built on top of the fact that the header has been "compacted" so this will be a bit of work, but I wanted to let you know that this is coming.

Thanks @maykar I was just looking into how to do exactly this, great to hear its in progress, what kind of time frame can we expect for this?

**Comment by maykar** [comment]
Whenever I find the time to work on it. I don't like to give time frames for bigger things like this as I will almost always disappoint those waiting and stress myself out trying to meet a self imposed deadline.

**Comment by maykar** [comment]
Found the time :) (wasn't nearly as bad as I though it'd be)

Added this in 1.3.4. `compact_header: false` will keep the default header and retain all other features.

**Comment by maykar** [comment]
Discussion on project name now that "Compact Custom Header" no longer fits the project.
https://community.home-assistant.io/t/compact-custom-header/83716/1057

**Comment by dy1io** [comment]
@maykar Thanks for your work on this! When I have `compact_header: false` would it be possible to also restore the side-bar to its default height? Here is what it looks like:

With CCH (`compact_header` `true` or `false`, its the same)
![image](https://user-images.githubusercontent.com/9081070/62424318-54c69f80-b69b-11e9-9031-330ab0045519.png)

With CCH Disabled
![image](https://user-images.githubusercontent.com/9081070/62424323-5b551700-b69b-11e9-8a86-0a693e3be7c9.png)


Also, less of an issue, but with `compact_header: false` the padding for the icons looks a little awkward. You wouldn't notice this if `compact_header` were `true`. Maybe just align the title text with the icons?

![image](https://user-images.githubusercontent.com/9081070/62424351-b981fa00-b69b-11e9-9863-3fbce47bfac3.png)

**Comment by maykar** [comment]
Should be fixed in the latest release 1.3.5
