### ISSUE TITLE
Multi range hiding of tabs

### ISSUE THREAD

**Issue by bjornesjogren** [maykar/compact-custom-header#178]
**Is your feature request related to a problem? Please describe.**
More of an inconvenience as the hiding one range of tabs works as well as individual

**Describe the solution you'd like**
I'm using the functionality to hide a range of tabs like 5 to 10 which works fine, But then I added a few tabs at the end that I wanted to hide as well so 5 to 10, 14 to 18 => Won't work. 5 to 10, 14,15,16,17,18 works. So as I said it's more of an inconvenience than a real problem but a solution would still be nice.

**Comment by maykar** [comment]
This will be fixed in the next release, ranges should have always worked like this. Thank you!

**Comment by maykar** [comment]
Fixed in 1.3.2
