### ISSUE TITLE
Feature: Add support for multiple rows

### ISSUE THREAD

**Issue by Redferne** [maykar/compact-custom-header#18]
This would be great for mobile devices in portrait mode. It is awkvard to be forced to scroll using the > arrow to get to the views which does not fit horizontally.
Thanks!

**Comment by maykar** [comment]
Wouldn't this be very similar to the default header?

**Comment by iantrich** [comment]
I do not like this idea personally. Kind of goes against the idea of "compact". Does swiping not work for you? You don't need to touch the arrow.

**Comment by maykar** [comment]
In fact if you're using this, you shouldn't see the arrows at all. Compact Custom Header should hide the arrows altogether and you can only swipe.

**Comment by Redferne** [comment]
Sure, swiping works. But it is extremely annoying since it takes me 6 swipes (6+ seconds) to get the last view. It would be an option to use multiple rows. Personally I think it would look more compact while using only icons. If you look at the screenshot. There is already lots of wasted space in HA. The spacing between entities and around icons are ridiculous. I know this is without the custom-header but still...
Two or three rows of tiny icons would look great, yes? 😉

![screenshot_20190115-010358_assistant](https://user-images.githubusercontent.com/2379821/51149629-39ad5300-1863-11e9-8551-742d7ca7d99a.jpg)

**Comment by iantrich** [comment]
These seems like an extreme case. I would probably recommend a different setup. Perhaps a main dashboard that is just navigation buttons to other views and each view has a back button that takes you to main and then you could hide the header all together. Or just expose that single tab in the header. Either way. That would be two clicks to get to any view, every time instead of the possible 6 swipes

**Comment by maykar** [comment]
I'm going to close this, but I am thinking on it. I'm not sure how feasible it will be, but with planned upcoming features there may be a solution.
