### ISSUE TITLE
[Feature Request] Multiple user conditions

### ISSUE THREAD

**Issue by arretx** [maykar/compact-custom-header#180]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a question about functionality.

**Describe the solution you'd like**
Is it currently possible to create a single exception and attach it to multiple users so I don't have to create the same exception repeatedly for each user?  We're using this in an office setting.

**Comment by maykar** [comment]
Thanks, this will definitely cut down on config length. I'll be adding the ability to use a list for `user:`

**Comment by maykar** [comment]
Added in 1.3.2
```
user: mayker, thekid, thewife
```
