### ISSUE TITLE
Compensate reduced sidebar header height

### ISSUE THREAD

**Issue by acshef** [maykar/compact-custom-header#181]
*Foreword: I'm aware that sidebar feature requests (#167) are not being implemented, but because this is related to existing functionality, I hope it can be evaluated further.*

## Describe the issue:
CCH Currently overrides the height of the `<div class="menu">` element in the `<ha-sidebar>` from `65px` down to `49px`.
![image](https://user-images.githubusercontent.com/9013284/62132080-991bff00-b299-11e9-910d-00b5c664b4d9.png)

However, it does not compensate for this reduction by increasing the rest of the sidebar. The following element `<paper-listbox>` has a height of `calc(100% - 196px)` so I expect that to get overridden to `calc(100% - 180px)`
![image](https://user-images.githubusercontent.com/9013284/62132250-f0ba6a80-b299-11e9-9968-d35836e447e7.png)

## Config YAML:
N/A

## HA and/or Browser Error:
None (layout issue)

## Versions and Browser:
* CCH v1.3.1
* Home Assistant 0.96.5
* Browser: Google Chrome x64 v75.0.3770.142
* YAML Mode

**Comment by maykar** [comment]
Thanks, this will be in the next release and I'll close this when it's up. This is absolutely a bug or rather an oversight on my part.

**Comment by maykar** [comment]
Fixed in 1.3.2
