### ISSUE TITLE
hide_config & hide_help

### ISSUE THREAD

**Issue by r3mcos3** [maykar/compact-custom-header#183]
## Describe the issue:

the options "hide_config" & "hide_help" still show  when set to true 

all other options still work

## Config YAML:

```
---
menu: show
voice: hide
swipe: true
options: clock
hide_config: 'true'
hide_help: 'true'
clock_format: 24
clock_am_pm: false
clock_date: false

```
## HA and/or Browser Error:

All other options work well

## Versions and Browser:

CCH Version: 1.3.3
HA Version: 0.97.0b1

Vivaldi  2.6.1566.44 (Stable channel) (64-bits)

YAML Mode

![vscode-snippet](https://user-images.githubusercontent.com/45529818/62409004-575cc280-b5d1-11e9-9eb6-1848315b3533.JPG)
![2019-08-03 09 23 32 10 10 50 90 249916ebf598](https://user-images.githubusercontent.com/45529818/62409008-65aade80-b5d1-11e9-997e-4fe71c6c3840.jpg)

**Comment by maykar** [comment]
I've tried the exact setup you are using (browser, config, versions the same, etc), but am still unable to reproduce this issue. 

I refactored menu item hiding in the latest version of CCH 1.3.4 in hopes that it might help. Please, try it and let me know.

**Comment by r3mcos3** [comment]
i'ts working now! Thanks
