### ISSUE TITLE
[Feature Request] Remove/reduce gap above cards in mobile with kiosk

### ISSUE THREAD

**Issue by noxhirsch** [maykar/compact-custom-header#188]
**Is your feature request related to a problem? Please describe.**
There's a gap above the cards in mobile view with kiosk (while the margin/padding on the sides is gone)
![padding](https://user-images.githubusercontent.com/30938717/63224291-62634580-c1c2-11e9-9c73-6d433d467bc8.PNG)

**Describe the solution you'd like**
It would be great to get rid of that as much as possible. This gap has two sources:
The easier one (I think) is a `padding` of 4px in `hui-view :host`
The other source is a margin of the first card. I don't know if it's possible to remove that (and not the margin of the other cards).

For me it would be already helpful if the 4px of hui-view are gone.

Thank you in avance!
Nico

**Comment by maykar** [comment]
This has been added in the latest pre-release 1.3.6

```
cch:
  view_css: "padding-top: 40px;"
```

More info here: https://community.home-assistant.io/t/compact-custom-header/83716/1109
