### ISSUE TITLE
TypeError if only one lovelace view/tab exists

### ISSUE THREAD

**Issue by thib5** [maykar/compact-custom-header#19]
Hi after 0.51.1 update the compact custom error stop working and I start to have this message : 

Uncaught TypeError: Cannot read property 'querySelectorAll' of null

**Comment by maykar** [comment]
Could you paste the full error please (the numbers preceding the type of error are very helpful), as well as your config? Also, confirm that you have done a "hard refresh".

**Comment by thib5** [comment]
Humm... honestly I revert to 0.84 when I see the bug and was waiting for a fix before updating again ... I will do another snapshot and update so I can give you the error

**Comment by maykar** [comment]
FWIW, I'm currently running this on 0.85.1 with no issues.

**Comment by thib5** [comment]
OK i did not respond before because it was workin but then i lost it again ... 

this is the log entry :

Log Details (ERROR)
Tue Jan 15 2019 14:49:01 GMT-0500 (heure normale de l’Est nord-américain)

https://mydomainname/local/custom-lovelace/compact-custom-header/compact-custom-header.lib.js?v0.2.7:31:20 TypeError: null is not an object (evaluating 'tabs.querySelectorAll')

**Comment by maykar** [comment]
Do you happen to only have one lovelace view? What does your config look like?

**Comment by thib5** [comment]
yes i have only one lovelace view ... i'm sory it's not the beter code but it work : 

https://pastebin.com/d5kAqXT3

**Comment by maykar** [comment]
Try adding an additional view to your lovelace and see if that fixes it.

**Comment by thib5** [comment]
it work ! sort of ... Now my background won't fit....  i have a white stripe at the bottom

**Comment by maykar** [comment]
Look at the background_image option in the readme. Will have a fix for the single tab issue in a bit.

**Comment by maykar** [comment]
Fixed in latest release
