### ISSUE TITLE
[Feature Request] Always show all tabs in edit mode

### ISSUE THREAD

**Issue by noxhirsch** [maykar/compact-custom-header#191]
**Is your feature request related to a problem? Please describe.**
I often edit my hidden tabs and always have to go in the menu to show them in edit mode.

**Describe the solution you'd like**
It would be nice if there's an option in the CCH settings (or only in yaml) to always show all tabs when in edit mode.

**Comment by maykar** [comment]
Added in the latest release. More info:

https://community.home-assistant.io/t/compact-custom-header/83716/1179
