### ISSUE TITLE
Adding header configuration at the beginning of a page adds margin to first column

### ISSUE THREAD

**Issue by MBlokhuijzen** [maykar/compact-custom-header#2]
I noticed when I add the compact-custom-header to the beginning of a page, it creates a html tag <compact-custom-header></compact-custom-header> and it seems like there's CSS added to it which causes it to use a few pixels. and "messes" up the alignment of the other entities.

#### Example

Page with compact-custom-header added
<img width="1397" alt="screenshot 2018-12-09 at 18 52 43" src="https://user-images.githubusercontent.com/1713390/49700880-e3eee680-fbe4-11e8-966e-fe3b3817f171.png">

Page without compact-custom-header added
<img width="1392" alt="screenshot 2018-12-09 at 18 52 54" src="https://user-images.githubusercontent.com/1713390/49700881-e5b8aa00-fbe4-11e8-80a5-7f360d15e031.png">

**Workaround:** Adding compact-custom-header to the end of a page still gives you the functionality without this issue.

**Comment by maykar** [comment]
Added your workaround as part of the installation instructions & important notes in readme. There's more than one reason to add this "card" as the last one in the view, so this may just be the fix. Thank you.

**Comment by MBlokhuijzen** [comment]
Awesome, thanks for the fast response. If it's added there and a good practice to add it last anyway you might aswell close this issue. Thanks for the awesome work on this component. Yesterday I setup a tablet and this was exactly what I needed!
