### ISSUE TITLE
view_css doesn't apply anymore since CCH 1.3.7

### ISSUE THREAD

**Issue by noxhirsch** [maykar/compact-custom-header#206]
## Describe the issue:
`view_css` doesn't apply anymore since CCH 1.3.7 (so it also doesn't work on 1.3.8)
After a rollback to version 1.3.6 it works again.

## Config YAML:
This is the relevant part - while I have this inside a condition, it doesn't work either in the normal config.

```yaml
view_css: 'margin-top:-8px;'
```
## HA and/or Browser Error:
No relevant errors in HA log and browser console.
Everything else in CCH is working.

## Versions and Browser:
CCH 1.3.8
HA 99.2
Chrome 77.0.3865.90
Storage Mode

**Comment by maykar** [comment]
I'm not sure if it's not working or if it's because the view element has changed a bit in 0.99 and the margin amount you used may need changed. Try increasing the value, even by 50 or so and see if there's a difference.

**Comment by noxhirsch** [comment]
I already tried `margin-top:-80px;`, `margin-top:80px;`, `margin-top:-80px!important;`, `margin-top:80px!important;` - that sadly didn't help.
Besides that, a rollback to CCH 1.3.6 helps - even with HA 99.2

**Comment by maykar** [comment]
Perfect thank you. Will check it out.

**Comment by maykar** [comment]
Just released 1.3.9 with fixes to address this. Let me know if that does it for you.

**Comment by noxhirsch** [comment]
Thank you very much! Now it works in normal mode - but in kiosk mode the view now stays on the hight of the original header and doesn't move with `view_css: 'margin-top:+/-XXpx;'`

**Comment by maykar** [comment]
Edit: Never mind, sorry. I see the issue. I'll get a fix in soon

**Comment by noxhirsch** [comment]
Here's the screenshot (no panel mode):
![header](https://user-images.githubusercontent.com/30938717/65641135-45553a00-dfec-11e9-8412-23f9511e2cd7.PNG)
I also get this in the console - only in kiosk mode:
![header2](https://user-images.githubusercontent.com/30938717/65641260-9bc27880-dfec-11e9-96cd-dba7cbc93776.PNG)

**Comment by maykar** [comment]
Sorry, bout that. Give 1.4.0 a try

**Comment by noxhirsch** [comment]
It's working 👍 Thank you!
