### ISSUE TITLE
Unexpted token error

### ISSUE THREAD

**Issue by andrewenriquez** [maykar/compact-custom-header#21]
**local/custom-lovelace/compact-custom-header/compact-custom-header.js?v0:7:1 Uncaught SyntaxError: Unexpected token <**

I get this error along with "Custom element doesn;t exist: compact-custom-header" every time. I'm on 0.85.1 of home assistant.

**Comment by maykar** [comment]
Either copy the js files from the raw files on GitHub or download them first
