### ISSUE TITLE
CCH menu doesn’t show in lovelace yaml mode

### ISSUE THREAD

**Issue by olijouve** [maykar/compact-custom-header#217]
Since i migrate to yaml mode, i can’t have CCH menu and panel showing up as we got an alert popup saying us the edit ui is not available when in yaml mode. 
Existing CCH config keeps running well through but we’re stucked if we want to modify CCH parameters. 

Could CCH menu link be moved elsewhere than in the lovelace configure UI submenu ?

## Config YAML:

```yaml

```

**Comment by maykar** [comment]
If you are using yaml mode then you need to configure CCH with yaml in the `ui-lovelace.yaml` file. Using yaml mode removes your ability to use the UI to edit config.  CCH's UI editor cannot work in yaml mode.
