### ISSUE TITLE
Views hidden by clock on small screen

### ISSUE THREAD

**Issue by tcastberg** [maykar/compact-custom-header#22]
### On small screens tab icons disappear.

Can be replicated by making your window narrow:
All icons:
![image](https://user-images.githubusercontent.com/2811983/51390784-89746e80-1b30-11e9-996a-cec7402eb0c3.png)

Missing icons:
![image](https://user-images.githubusercontent.com/2811983/51390805-a0b35c00-1b30-11e9-99f8-0e1af5d24076.png)

**Comment by iantrich** [comment]
Can you not scroll to them?

**Comment by tcastberg** [comment]
You know what? I thought I did try that, but must have fat-fingered it. Indeed I am able to scroll.
