### ISSUE TITLE
state requires to be in quotes

### ISSUE THREAD

**Issue by iptvcld** [maykar/compact-custom-header#223]
Not Working:
  conditional_styles:     
    - entity: input_boolean.darkmode
      condition:
        state: on
      background: grey  

Working: (the state needs to be in quotes) - the readme shows that there are no quotes.
conditional_styles:     
    - entity: input_boolean.darkmode
      condition:
        state: "on"
      background: grey

**Comment by maykar** [comment]
Thanks, will update the readme
