### ISSUE TITLE
Small gap below header in HA 0.100

### ISSUE THREAD

**Issue by cnflx** [maykar/compact-custom-header#226]
Home Assistant 0.100 generates a small margin beneath the header. 

In my installation I've manually adjusted line 495 from

_view.style.marginTop = "-48.5px";_

to

_view.style.marginTop = "-52px";_

That was sufficient to fix the problem for me but I'm not sure if there's more to it.

**Comment by maykar** [comment]
Looks like this only effects panel view, will add a fix in the next release.
