### ISSUE TITLE
TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by tjorim** [maykar/compact-custom-header#23]
Currently on Home Assistant 0.86.0 beta. First use of this custom 'card' so I don't know if I would have this issue on previous releases. However, [recently the routing has changed](https://github.com/home-assistant/home-assistant-polymer/compare/20190116.0...20190121.1) which probably introduced this bug.

```
VM581 compact-custom-header.lib.js:23
 TypeError: Cannot read property 'querySelector' of null
    at VM581 compact-custom-header.lib.js:18
```

**Comment by maykar** [comment]
I am aware and a fix is being worked on
