### ISSUE TITLE
[Feature Request] An actual unique ID for each tab

### ISSUE THREAD

**Issue by kmycek** [maykar/compact-custom-header#231]
**Is your feature request related to a problem? Please describe.**
The "Tab IDs" to hide seems to be positional to where the tab appears in the raw config. When I move a tab I have to reset the entire hidden tab config (including any hidden tab configs for exceptions).

**Describe the solution you'd like**
If each tab had a unique identifier (guid or even integer) that it retained when moved - that would greatly improve the UX with using this feature. Otherwise, great tool. Thank you!

**Comment by maykar** [comment]
This is why the feature to use a tabs title or path is also an option. Either give your views a title or path and then use that as the unique identifier.

**Comment by kmycek** [comment]
OK, thanks. I'll try that. I didn't see that in the documentation, so please excuse my naïveté.
