### ISSUE TITLE
SecurityError for History Push

### ISSUE THREAD

**Issue by deluxestyle** [maykar/compact-custom-header#235]
## Describe the issue:
Swiping stops/breaks on ios after a few slides (see attached gif)
In the header it seems still to swipe but the view is not changing

## Config YAML:
`cch:
  main_config: true
  menu: show
  notifications: show
  options: show
  swipe: true
  exceptions:
    - conditions:
        user_agent: iPhone
      config:
        options: show
        notifications: overflow
    - conditions:
        user: anita
      config:
        hide_tabs: 7`

## HA and/or Browser Error:
Following error happens during swiping on ios (either the app or in safari)
`2019-10-31 08:08:02 ERROR (MainThread) [frontend.js.latest.201910022] http://my.url/frontend_latest/app.37dcadb7.js:724:266382 SecurityError: Attempt to use history.pushState() more than 100 times per 30 seconds`

if this error happens then I need to restart the app or my safari browser

![ezgif-1-557564960697](https://user-images.githubusercontent.com/662779/68458962-58227780-0204-11ea-885e-a510c20e2a30.gif)

## Versions and Browser:
ios 13.2.2
safari
ios Companion app 1.5 / 2.0 beta

**Comment by maykar** [comment]
Bear with me on this issue. CCH is being replaced with a new project that I'm currently working on, while I'm doing that I'll also be rewriting swipe navigation. They will be separate projects once all is finished, but without loss in functionality.

**Comment by deluxestyle** [comment]
Thanks for the update. 
And thank you for all the hard work
