### ISSUE TITLE
Option for side panel elements to be tabs in header

### ISSUE THREAD

**Issue by dooz127** [maykar/compact-custom-header#237]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I'd like to have just a single navigation bar for the front-end so it'd be nice if there was an option to move all of the side panel elements into header tabs.

**Comment by maykar** [comment]
Since CCH only operates inside of Lovelace I need to keep any interaction with the sidebar to a minimum. The sidebar is required for navigation outside of Lovelace, so something like this should be added to core or handled with an addon that is available across the entire frontend.

**Comment by dooz127** [comment]
Thanks for the consideration. Makes sense.
