### ISSUE TITLE
[Feature Request] Custom CSS as theme variable

### ISSUE THREAD

**Issue by capstan1** [maykar/compact-custom-header#238]
**Is your feature request related to a problem? Please describe.**
Some options of custom CSS are interesting options for theme developers. For example I'd like to add a minimum margin to the view, so that cards on mobile devices are not displayed without margin.

![1](https://user-images.githubusercontent.com/17147867/68921529-58c58b80-0779-11ea-8940-33fae75b1a86.jpg)

Probably there are various other variables interesting for other people I'm not thinking off.

**Describe the solution you'd like**
It would be nice to add the custom CSS values to the theme variables already available. With this new options I could have far more options for deciding how the theme will look for the end user.

Thanks for your great Custom card!

**Comment by maykar** [comment]
I'm not sure how this would work exactly as theme variables can really only have one property like:
`primary-color: "#000000"` would be used with something like  `menu_color: var(--primary-color)`

Whereas, the custom css options are inserting full CSS into the elements, like `view_css: "padding: 5px; margin: 4px;"`

I don't believe there would be an option that would be as easy as just sharing your config from CCH.
