### ISSUE TITLE
 New version  (0.102) of HA seems to have broken something.

### ISSUE THREAD

**Issue by BrettWa** [maykar/compact-custom-header#240]
It seems the latest version of home assistant has broken something with the alignment of the top banner icons. My first icon is behind the drop down menu icon - and can't be clicked. I also get the following in the error log, not sure if related?

https://MYURLm/local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1:651:17 Uncaught TypeError: Cannot read property 'style' of null

![Image of Yaktocat](https://i.ibb.co/tsSgxZg/Capture.jpg)

**Comment by maykar** [comment]
https://community.home-assistant.io/t/compact-custom-header/83716/1327?u=mayker

Remove any voice options. For the moment the voice button should only be "show" or "hide"

**Comment by maykar** [comment]
CCH is being replaced soon with a completely new project. CCH has many issues and small changes in HA can cause big issues in multiple places in CCH (not HA’s fault).

The new project aims to fix these issues, make it much easier to fix things when something in HA changes, add many new features not possible with how CCH currently works, and much more.

I apologize that I cannot give as much time to fixing and troubleshooting CCH at the moment, but be assured it’s for the best. That being said, please be patient while it is being worked on.

**Comment by BrettWa** [comment]
It seems the issue is being caused by the  "Always hide the sidebar" option  in HA, when not set, everything aligns.

Looking forward to the new project!

**Comment by maykar** [comment]
Going to keep this open in case others have the same issues, thanks!

**Comment by iptvcld** [comment]
My mobile features have stopped working. No longer able to swipe and no longer compact

**Comment by maykar** [comment]
Read above for possible fix and explanation of why I (probably) won't look into it. Also, when posting an issue you should always post your config and any errors found.

**Comment by BoneheadFraggle** [comment]
> 
> 
> My mobile features have stopped working. No longer able to swipe and no longer compact

I noticed the same while using https://github.com/thanksmister/wallpanel-android however, it works fine with Chrome. I guess it's something with a old webview or something.

**Comment by iptvcld** [comment]
Bang on! Thanks, just cleared my chrome history on my mobile device and all my customizations are back!
