### ISSUE TITLE
Single tab user agent view error

### ISSUE THREAD

**Issue by BioGeekJoey** [maykar/compact-custom-header#26]
I'm not getting the user agent to work with usernames. 

my config
`user_agent: 'username1, username2, username3'`
`user_agent_views:`
`  - 5`
`  - '0,1,2'`
`  - '0,1,2'`
`  - 2`
`clock: 'notification, menu'`
`clock_format: 24`
`menu: 'false, true'`
`notification: true`
`voice: true`
`type: 'custom:compact-custom-header'`

It's also spitting out this error every time I load a view, not sure if this is related?
`https://my.homeassistant.domain/local/custom-lovelace/compact-custom-header/compact-custom-header.lib.js?v0.2.9:219:49 Uncaught TypeError: Cannot read property 'click' of undefined`

**Comment by maykar** [comment]
Until I fix, just add a number to the two user_agent_views that only have one digit. Something like this:

```
user_agent_views:
- '5,42'
- '0,1,2'
- '0,1,2'
- '2,42'
```

**Comment by maykar** [comment]
This is no longer an issue on the latest release v1.0.0b0
