### ISSUE TITLE
Custom-updater does not work by default when following instructions in the readme

### ISSUE THREAD

**Issue by arigit** [maykar/compact-custom-header#29]
**Describe the bug**
Custom-updater does not work by default when following the installation instructions in the readme

The customization does work, but custom-updater does not list the card in its custom card list.

This is the issue:

```
This goes into under "resources:" in ui-lovelace.yaml or using the raw config editor.

- url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v0
  type: js
```

In order for custom-updater to actually detect this card for the first time, this is needed instead:

```
resources:
- url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1
  type: js

```

Following the instructions, it would seem that the "v=0.0.1" is only needed when NOT using custom-updater. Actually, v=0.0.1 is needed in order for custom-updater to work for the first time with this card.

**Comment by maykar** [comment]
Updated readme, this was a typo
