### ISSUE TITLE
No clock when using Firefox

### ISSUE THREAD

**Issue by Blink515** [maykar/compact-custom-header#35]
**Describe the bug**
Clock is not displayed when using Mozilla Firefox but displays as expected with Google Chrome. 

**Config**
`      - id: 73595f72d1
        type: custom:compact-custom-header
        header: true
        menu: true
        notification: true
        voice: true
        options: true
        tabs: true
        clock: voice
        clock_format: 12
        clock_am_pm: true
        disable: false
        dir: '/local/compact-custom-header/'`

**Error**
No error messages in Firefox's dev console or home assistant logs.

**Screenshots**
Chrome on left and Firefox on right

![screen shot 2019-02-04 at 9 17 20 pm](https://user-images.githubusercontent.com/979890/52253034-cecfc480-28c2-11e9-8894-e466ba93c521.png)

**Version**
Home Assistant Version 86.4
Compact Custom Header Version 0.2.9
Firefox 64.0.2
Chrome 72.0.3626.81

**Additional context**

**Comment by wiuwiu** [comment]
@Blink515 this happends when you use `clock: voice` because AFAIK the voice is not available in the Firefox.
I have a question how did you get AQI? From BME680 sensor? and on which platform - Arduinio, ESP?

**Comment by maykar** [comment]
That would explain it, thanks @wiuwiu . Voice Icon just doesn't display on firefox and is not due to this card. The version just released also fixes remaining issues with firefox, so I'm closing this one.

**Comment by Blink515** [comment]
Thanks @wiuwiu  AQI isn't from a BME sensor it's a component I'm using.  https://www.home-assistant.io/components/sensor.waqi/
