### ISSUE TITLE
[Feature Request] show_tabs

### ISSUE THREAD

**Issue by ohminy** [maykar/compact-custom-header#50]
Is there any way to change from [hide_tabs] to [show_tabs].
Because when i add some new view, every time i have to change exceptions conditions of hide_tabs for all devices.

**Comment by maykar** [comment]
show_tabs is on my list of features to add so stay tuned. This will not replace hide_tabs, but be in addition to.

**Comment by kknishev** [comment]
Sorry for offtop, but is any way to increase height from 48px to 64px?

**Comment by maykar** [comment]
@KKnishev  It's not something I'm going to add to the card, but I've mentioned how you can edit it yourself here:
https://community.home-assistant.io/t/compact-custom-header-custom-user-device-views/83716/386

**Comment by kknishev** [comment]
@maykar thanks a lot! -48px is what I want ;)

**Comment by maykar** [comment]
Added in 1.0.0b6
