### ISSUE TITLE
After upgraded from 1.0.0 to 1.0.0b2 it doent work....

### ISSUE THREAD

**Issue by ohminy** [maykar/compact-custom-header#51]
Thx. for development this awesome custom card.

few minutes ago.. After I upgraded from 1.0.0 to 1.0.0b2 it doent work somehow.....

is there any changes??

https://ha.ohminy.com/lovelace/default_view?clear_cch_cache:0:0 Uncaught SyntaxError: The requested module './compact-custom-header.js' does not provide an export named 'LitElement'
Service system_log/write called.

https://ha.ohminy.com/local/custom_ui/clock-card.js:83:10 Uncaught ReferenceError: moment is not defined
Service system_log/write called.

etc...

**Comment by maykar** [comment]
Please submit this as a bug, not a feature request and fill out the template info
