### ISSUE TITLE
Error after update using by custom component updator

### ISSUE THREAD

**Issue by ohminy** [maykar/compact-custom-header#52]
I have some errors after update using by custom component updator, today.
0.0.1 -> 1.0.0b2

After update all, it was chaged like that
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=1.0.0b2

so I changed as below, and fixed.
  - url: /local/custom-lovelace/compact-custom-header/compact-custom-header.js?v=0.0.1

**Comment by maykar** [comment]
Sounds like you where having a caching issue. Please, use the bug report template. It's there to help me get all the info I need to troubleshoot your issues.
