### ISSUE TITLE
FireOS Outdated Webview

### ISSUE THREAD

**Issue by radioraheem** [maykar/compact-custom-header#59]
## Describe the bug:
Outdated Webview in FireOS results in card not working.  Browsers on the Fire tablet that utilize the OS Webview display an error in the card, but if you install Chrome on the device it works fine.
Use case for issue:  CCH is ideal for use on a tablet interface to Home Assistant, and because apps like Fully Kiosk Browser use the FireOS webview it will not work.  Chrome browser no longer allows a fullscreen mode so it cannot be used for a workaround. 

Very possible this is not fixable until Amazon updates the webview version in a future OS update, but wanted to make you aware of it. 

## Config:
`- type: 'custom:compact-custom-header'
        main_config: true
        options: clock
        voice: hide
        notifications: hide
        clock_format: 12
        clock_am_pm: true`

## Error:
In Fully Kiosk Browser:  
Custom element doesn't exist:  compact-custom-header

In Chrome:
Works fine

## Versions:
Version of this card:  Latest
Home Assistant version: 0.88.0
Browser type and version:  Fully Kiosk Browser for FireOS, latest
YAML or Storage Mode:  Storage

**Comment by iantrich** [comment]
FireOS webview doesn't support custom elements. Would need to use babel and something like rollup.js.

e.g.
https://github.com/kalkih/mini-media-player/blob/master/package.json
https://github.com/kalkih/mini-media-player/blob/master/rollup.config.js

**Comment by maykar** [comment]
<strike>User pjv from the HA forums was kind enough to port this for legacy devices and he will be trying to keep it current. I do not provide support for this solution.

https://community.home-assistant.io/t/compact-custom-header-custom-user-device-views/83716/371</strike>

I now maintain the legacy device version found here: [CCH for older/unsupported devices.](https://github.com/maykar/compact-custom-header/issues/185)

**Comment by radioraheem** [comment]
Legacy version worked like a charm.  Thank you!

**Comment by volpmatt** [comment]
> Legacy version worked like a charm. Thank you!

Can you talk me through how you implemented this legacy version, step by step please?

**Comment by maykar** [comment]
If anyone was still having issues with this I'm now maintaining a legacy device version. Found here: [CCH for older/unsupported devices.](https://github.com/maykar/compact-custom-header/issues/185)
