### ISSUE TITLE
Compact Header + Background Image

### ISSUE THREAD

**Issue by muspelheim** [maykar/compact-custom-header#60]
## Describe the bug:
When Compact header enabled background didn't fill all space, if disabled background is correct, pay attention to the dark line at the bottom
![456](https://user-images.githubusercontent.com/1663352/53443266-57520880-3a1c-11e9-90bb-30d697e074c7.png)

## Config:
`background: center / cover no-repeat url("/local/images/main_background.jpeg")`

## Versions:
1.0.1b2

**Comment by maykar** [comment]
From the readme:

| | | | | |
|-|-|-|-|-|
|background_image|boolean|false||Set to true if you use a background image, otherwise the background will not fill the window.

**Comment by muspelheim** [comment]
@maykar thank you, sorry for my stupidity
