### ISSUE TITLE
[Feature Request] Date Formatting

### ISSUE THREAD

**Issue by bacco007** [maykar/compact-custom-header#61]
It would be good to be able to be able to format the date (even if its just to swap Month and Day)

**Comment by kloggy** [comment]
Can I second this.
Without wishing to be too picky, I'd like the date text to be smaller than the time, at the moment it doesn't to my eyes look 'right'.

![image](https://user-images.githubusercontent.com/38220016/53561084-cecf8700-3b45-11e9-8e84-b424f3fe0349.png)

And definitely would prefer to be able to format as d/m (at least).

Thanks.

**Comment by maykar** [comment]
Will add date format as a config option. Currently, it's changed automatically with HA language preferences, but it should be an option as well. I'm also playing around with the look of it, so stay tuned.

**Comment by kloggy** [comment]
That's great news, thanks!

> it's changed automatically with HA language preferences

Perhaps we need a change request to HA to have an English (UK) language option?

**Comment by maykar** [comment]
Closed this as I fixed the styling, completely forgot to add month/day formatting. Reopening.

**Comment by maykar** [comment]
Nevermind then, opened a new one #75 . Burned by my own bot.

**Comment by maykar** [comment]
Formatting override added in 1.0.1b6. Check `date_locale:` option in readme.
