### ISSUE TITLE
Clarify the usage of Name (not Username) and case sensitivity

### ISSUE THREAD

**Issue by BoneheadFraggle** [maykar/compact-custom-header#68]
**Is your feature request related to a problem? Please describe.**
This is not a problem, just a small suggestion to make the cofiguration even smoother:
It is not obvious that you are supposed to use Name in exceptions, since Usernames are more common in other systems.

**Describe the solution you'd like**
Add (or if it's already there) make it clearer that exceptions uses the Name, not the Username (which was my default guess), and also that exceptions are case sensitive.

**Additional Context**
Thank you so much for your effort!

**Comment by maykar** [comment]
Thanks, this is a strange one
