### ISSUE TITLE
[Feature Request]Align time and date

### ISSUE THREAD

**Issue by xicoxicao** [maykar/compact-custom-header#77]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would it be possible to have time and date center aligned rather than right aligned?
I think it would look better, but this is just me.

**Additional Context**

**Comment by maykar** [comment]
I don't think I'll be adding this as a feature, but you can edit the card to do this:

On line 549 find `text-align: ${clockAlign};` and make it `text-align: center;`
